version: 0.2

phases:
  install:
    {
      "runtime-versions": { nodejs: "14" },
      commands: ["npm install -g yarn", "yarn install --immutable"],
    }
  build: { commands: ["yarn build"] }
  post_build:
    {
      commands:
        ["aws s3 sync ./build s3://portfolio-assets-us-east-1/build/ --delete"],
    }
